### ISSUE TITLE
the  copy_unknown_words.py can not be used 

### ISSUE THREAD

**Issue by liangssGift** [rsennrich/nematus#13]
Hi Rico,
Have you considered to output the original word without the UNK symbol? I found that the script copy_unknown_words.py in the UTILS folder can not replace the unknown words in target sentences with their aligned words in source sentences.
Do you have any suggestions ?

**Comment by rsennrich** [comment]
I changed the script to now use the format that translate.py produces with the option '--output_alignment'. You can try again to see if this works.
