### ISSUE TITLE
Approximated softmax

### ISSUE THREAD

**Issue by mattiadg** [rsennrich/nematus#20]
Hi,

I am wondering why the last layer is a softmax and not an approximated version such as Hierarchical softmax or noise contrastive estimation.
Maybe the improvement on time performance wouldn't be significant?

Thanks,
Mattia

**Comment by Avmb** [comment]
As far as I understand, noise contrastive estimation is less accurate than softmax. Other approximations may work better, but it takes time to implement and test them. Feel free to contribute if you are interested.

Best,
Antonio
