### ISSUE TITLE
How can I get the context vector at translation time?

### ISSUE THREAD

**Issue by yftah89** [rsennrich/nematus#22]
in translation time I would like to get the context vector(with soft attention) and words embeddings  for each word wi with all the alphas and hidden state, for example (english to french):

> h1   h2     h3          h4    h5       h6 
 |      |         |             |       |          |
the boy played -> Le garçon jouait
 |      |         |             |       |          |  
x1   x2      x3          x4    x5        x6

if we look at the word "garçon" at translation time, I would like to get alpha1*h1+alpha2*h2+alpha3*h3 sum, and h1,h2,h3,alpha1,alpha2,alpha3 for this word.
I would also like to get the source word embeddings(x1,x2,x3)

**Comment by rsennrich** [comment]
Hello,

there is code to output the attention weights, and you will have to 
follow the same principle if you want to output other internal states of 
the model at translation time:

  - add the state(s) you're interested in to the outputs of the theano 
function in build_sampler()
  - in gen_sample(), make sure that the state you're interested in is 
saved/returned for each hypothesis (again, analogously to what is 
currently done with alignment)
  - in translate.py, make sure that the information is returned by 
_translate(), and define how you want the information printed in main()

best wishes,
Rico

**Comment by yftah89** [comment]
Tnx for the quick answer Rico :)
