### ISSUE TITLE
number of next word predictions at translation time

### ISSUE THREAD

**Issue by saitarslanboun** [rsennrich/nematus#28]
Dear nematus community, 

It has been couple of months I have started to deal with neural machine translation. I have a question related to nematus code, and I am sorry if it is so primitive for you.

In translation time, in the function **gen_sample()** under **nmt.py**, **next_w** predictions are not one, but it varies "as I have experimented up to now" up to 5, why is it?

So basically, I am getting alignment vector, context vector and next word predictions at translation time under the following loop:

**# x is a sequence of word ids followed by 0, eos id
    for ii in xrange(maxlen):**

But the number of values at each time step at alignment vector, context vector and next word vector is more than one, up to 5.

Why?

Thanks for your time and answer.

Kind Regards,

**Comment by yftah89** [comment]
Hi, I think that you get one alignment vector, context vector and next word vector for each one of the beams in your beam search, try to run the training with -k 3 ( -k is for the beam search's size) for example and if you will find out that instead of 5 of each you get 3 of each then my guess is probably correct

**Comment by saitarslanboun** [comment]
Hi @yftah89 so you mean that the size of the vectors are basically beam search size right?

**Comment by yftah89** [comment]
Yes, this is exactly my assumption, an easy way to verify it is to simply change the beam search default value (5 if I'm not wrong) the different one by adding -k 3 for example and to check if you get 3 of a kind for all of the things you mentioned above.


Regardless, if you use beam search you will have to save all of those values for each beam if not at the point you are talking about than in some other point.
