### ISSUE TITLE
Cost 0.0 in training

### ISSUE THREAD

**Issue by mattiadg** [rsennrich/nematus#33]
Hi!

I'm running the last version of Nematus in a machine with Ubuntu16.04, cuda-8.0 and Theano 0.9, but when I run test_train.sh the cost of the iteration is 0.0. 
The same thing happens when running an actual training on parallel data (IWSLT 2016 en-fr). The objective functions is cross-entropy.
I used previous versions of nematus but I've never encountered this problem

**Comment by rsennrich** [comment]
Thanks for pointing this out - fixed.
