### ISSUE TITLE
alpha_c not supported yet still in the README

### ISSUE THREAD

**Issue by roeeaharoni** [rsennrich/nematus#35]
Just pulled the latest version and got:

nmt.py: error: unrecognized arguments: --alpha_c 0.0

Yet it is still shown in the README documentation. Was it renamed?

**Comment by rsennrich** [comment]
Hi Roee,

Sorry about the out-of-date README, it is now updated.

I removed alignment regularization a while ago (commit 2f7e80e02cfaf66e0f23c256a125b4ee8659d319) in an attempt to remove some of the unused/untested options. I'm happy to take it back in if anybody makes a case for it, but I can see that you also set it to 0.

**Comment by roeeaharoni** [comment]
Yes, didn't use it as well. Thanks!
