### ISSUE TITLE
Domain Adaptation with nematus

### ISSUE THREAD

**Issue by saitarslanboun** [rsennrich/nematus#41]
Hi folks,

I have trained a translation model with a dataset. After 510000th iteration, I have killed the training, and started a new training with a new dataset, by using the last 510000th model I had. For this reason, I have created a new models folder, and copied model.iter510000.npz as model.npz, and model.iter510000.npz.gradinfo.npz as model.npz.gradinfo.npz. But I forgot to copy model.iter510000.progress.json to my new models file.

Theoretically, it shouldn't effect the fact that I continue training from 510000th iteration, right? Because since I have not copied progress.json file, the output of the code shows like I have started from 0.

**Comment by rsennrich** [comment]
Yes, deleting the *.progress.json only resets the counter to 0, but 
doesn't affect the learned weights.

best wishes,
Rico
