### ISSUE TITLE
json and pkl files missing

### ISSUE THREAD

**Issue by senisioi** [rsennrich/nematus#9]
Hi, I think the translate.py script (at line 111) should say something more meaningful when both the .pkl and .json files are missing. I'm currently missing both files, I think it's because saveFreq was not set properly.

**Comment by scfrank** [comment]
If you are trying to translate a best_bleu.npz model, you might need to
copy the $MODEL.dev.npz.json file to $MODEL.best_bleu.npz.json.

This is a bug/missing in the wmt-16 sample validate.sh script.

**Comment by senisioi** [comment]
Thanks, this seems right.
